[nginx]
20.84.54.45 ansible_user=adminuser ansible_password=Xxpaladin$05 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[jenkins]
74.235.50.185 ansible_user=adminuser ansible_password=Xxpaladin$05 ansible_ssh_common_args='-o StrictHostKeyChecking=no'